version: "3.1"

services:
  frontend:
    image: skybitches-frontend
    ports:
      - "8000:80"

  backend:
    image: skybitches-backend
    ports:
      - "3000:3000"
    restart: always

  mongo:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - ./backend/data:\data\db

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}

networks:
  default:
    external: true
    name: nginxproxy
