version: "3.1"

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: AFA
      MONGO_INITDB_ROOT_PASSWORD: AFA
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: AFA
      ME_CONFIG_MONGODB_ADMINPASSWORD: AFA
      ME_CONFIG_MONGODB_URL: mongodb://AFA:AFA@mongo:27017/
