version: "3.8"

services:
  frontend:
    image: skybitches-frontend:latest
    ports:
      - "8000:8000"
    restart: always

  backend:
    image: skybitches-backend:latest
    ports:
      - "3001:3000"
    restart: always

networks:
  default:
    external: true
    name: nginxproxy

volumes:
  mongodb:
    external: true