version: "3.1"

services:
  frontend:
    build: ./frontend/.
    environment:
      VIRTUAL_HOST: "skybitches.at"
      VIRTUAL_PORT: 8000
      # LETSENCRYPT_HOST: "skybitches.at"
    ports:
      - "8000:8000"

  backend:
    build: ./backend/.
    ports:
      - "3000:3000"
    restart: always

  mongo:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:\data\db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}