defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["monitoruser:$apr1$vvm6D8o8$8khJZLGUcv4Kmw4BewvLY/"]

[api]
entrypoint="dashboard"

[entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
[entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "webmaster@domain.example"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "domain.example"
watch = true
network = "web"